name: Build Kivy APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip zip unzip openjdk-11-jdk build-essential libssl-dev libffi-dev libxml2 libxml2-dev libxslt1-dev zlib1g-dev git

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython

    - name: Build the APK
      run: |
        buildozer init || true
        buildozer -v android debug
